export enum FormTypes  {
CREATE_NEW_DATA_FORM = "CREATE_NEW_DATA_FORM",
DELETE_DATA_FORM = "DELETE_DATA_FORM",
UPDATE_DATA_FORM = "UPDATE_DATA_FORM",
FETCH_ALL_DATA_FORMS = "FETCH_ALL_DATA_FORMS",
START_LOADING = "START_LOADING",
END_LOADING = "END_LOADING",
ERROR = "ERROR",

}